# BPN FOR IRIS DATASET

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [ ]:
data = load_iris()
print(" my input parameter\t\n\n",data.data)

# here x are my input (SepalLengthCm ,SepalWidthCm ,PetalLengthCm ,PetalWidthCm
X=data.data
# here y is my taget ( 3 kinds os species - 0:Iris-setosa , 1:Iris-versicolor ,2:Iris-virginica )
y=data.target

 my input parameter	

 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.

In [ ]:
print(" my target classes \t\n\n",data.target)

 my target classes 	

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
 #It converts categorical data into dummy or indicator variables
 # here i have choosen y ( target) to be converted ito numerical limit 3
y = pd.get_dummies(y).values
y[:3]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]], dtype=uint8)

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=20)

In [ ]:
print(y_train)

[[0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]
 [0 0 1]
 [0 0 1]
 

In [ ]:
learning_rate = 0.1
iterations = 5000
N = y_train.size
input_size = 4
hidden_size = 2 
output_size = 3  
results = pd.DataFrame(columns=["mse", "accuracy"])

In [ ]:
# Initialize weights
np.random.seed(10)
# hidden layer
W1 = np.random.normal(scale=0.5, size=(input_size, hidden_size))  
#weight layer
W2 = np.random.normal(scale=0.5, size=(hidden_size , output_size)) 

In [ ]:
def sigmoid(x):
    
      
    return 1 / (1 + np.exp(-x))

def mean_squared_error(y_pred, y_true):
    return ((y_pred - y_true)**2).sum() / (2*y_pred.size)
    
def accuracy(y_pred, y_true):
    acc = y_pred.argmax(axis=1) == y_true.argmax(axis=1)
    return acc.mean()

In [ ]:
for itr in range(iterations):    
    
    # feedforward propagation
    # on hidden layer
    Z1 = np.dot(X_train, W1)
    A1 = sigmoid(Z1)

    # on output layer
    Z2 = np.dot(A1, W2)
    A2 = sigmoid(Z2)
    
    
    #  error is calculated herz
    mse = mean_squared_error(A2, y_train)
    acc = accuracy(A2, y_train)
    results=results.append({"mse":mse, "accuracy":acc},ignore_index=True )
    
    # bpn here : go back and updatw weights
    E1 = A2 - y_train
    dW1 = E1 * A2 * (1 - A2)

    E2 = np.dot(dW1, W2.T)
    dW2 = E2 * A1 * (1 - A1)

    
    # weight updates
    W2_update = np.dot(A1.T, dW1) / N
    W1_update = np.dot(X_train.T, dW2) / N

    W2 = W2 - learning_rate * W2_update
    W1 = W1 - learning_rate * W1_update
    print("MSE \n\n\t:" , mse)
    print("ACcuracy \n\n\t :",acc)
    print('weight w1 \n\n\t :',W1)
    print('weight w2 \n\n\t :',W2)

Streaming output truncated to the last 5000 lines.
	 : [[ 0.18884692  0.58000142]
 [-1.39873587  0.93192355]
 [ 0.92027256 -1.82373888]
 [ 0.45264135 -0.56800874]]
weight w2 

	 : [[-2.50042281 -0.16686176  0.24355013]
 [ 2.2475922  -1.70037164 -2.08931722]]
MSE 

	: 0.05958500817438379
ACcuracy 

	 : 0.676923076923077
weight w1 

	 : [[ 0.18880598  0.58002778]
 [-1.39878544  0.93197428]
 [ 0.92033075 -1.82379552]
 [ 0.45267716 -0.56803766]]
weight w2 

	 : [[-2.50061836 -0.16684911  0.24359724]
 [ 2.2477216  -1.700485   -2.08955107]]
MSE 

	: 0.059583598204682196
ACcuracy 

	 : 0.676923076923077
weight w1 

	 : [[ 0.18876505  0.58005412]
 [-1.39883499  0.932025  ]
 [ 0.92038891 -1.82385212]
 [ 0.45271297 -0.56806658]]
weight w2 

	 : [[-2.50081387 -0.16683647  0.24364434]
 [ 2.24785096 -1.70059833 -2.08978487]]
MSE 

	: 0.059582188972470335
ACcuracy 

	 : 0.676923076923077
weight w1 

	 : [[ 0.18872412  0.58008047]
 [-1.39888453  0.93207569]
 [ 0.92044705 -1.8239087 ]
 [ 0.45274876 -0

BPN IRIS ACCURACY = 0.67

# RBF FOR IRIS DATASET 


IMPORTING NECESSARY PACKAGES

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import math
from sklearn.metrics import accuracy_score

LOADING DATASET

In [ ]:
dataset = pd.read_csv('/content/iris.csv',sep=None)
dataset.head()
col_to_use = ['sepal.length','sepal.width','petal.length','petal.width']
data = dataset.drop(col_to_use,axis=1)
data.head()
data = data.apply(LabelEncoder().fit_transform)

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


DISPLAYING FEATURES

In [ ]:
dataset.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

DISPPLAYING TARGET VALUE

In [ ]:
data.head()

variety
0        0
1        0
2        0
3        0
4        0

CHOOSEING X AND Y

In [ ]:
data_rest = dataset[col_to_use]
data_rest.head()
dataset2 = pd.concat([data_rest,data],axis=1)
dataset2.head()
X= dataset2.drop('variety',axis=1)
y= dataset2['variety']

SPLITTING INTO TEST AND TRAIN DATA

In [ ]:
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size= 0.33, random_state= 4)


SCALE THE DATA USING STANDARD SCALER

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

DETERMINING THE CENTER OF NEURONS USING KMEANS

since neuro should be more than input : we have 4 input so i gave no of neuron( centroid points) to 6

In [ ]:
X_train
K_cent= 6
km= KMeans(n_clusters= K_cent, max_iter= 100)
km.fit(X_train)
cent= km.cluster_centers_

SETUP THE MATRIX

In [ ]:
max=0 
for i in range(K_cent):
	for j in range(K_cent):
		d= np.linalg.norm(cent[i]-cent[j])
		if(d> max):
			max= d
d= max

sigma= d/math.sqrt(2*K_cent)

FINDING THE WEIGHT MATRIX TO TRAIN THE NETWORK

In [ ]:
shape= X_train.shape
row= shape[0]
column= K_cent
G= np.empty((row,column), dtype= float)

for i in range(row):
  for j in range(column):
    dist= np.linalg.norm(X_train[i]-cent[j])
    G[i][j]= math.exp(-math.pow(dist,2)/math.pow(2*sigma,2))

In [ ]:
GTG= np.dot(G.T,G)
GTG_inv= np.linalg.inv(GTG)
fac= np.dot(GTG_inv,G.T)
W= np.dot(fac,y_train)
row= X_test.shape[0]
column= K_cent
G_test= np.empty((row,column), dtype= float)
for i in range(row):
	for j in range(column):
		dist= np.linalg.norm(X_test[i]-cent[j])
		G_test[i][j]= math.exp(-math.pow(dist,2)/math.pow(2*sigma,2))

ACCURACY

In [ ]:
prediction= np.dot(G_test,W)
prediction= 0.5*(np.sign(prediction-0.5)+1)

score= accuracy_score(prediction,y_test)
print(score.mean())


0.68


RBF IRIS ACCURACY = 0.68